services:
  identity.api:
    container_name: identity_container
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "5001:8080"
    depends_on:
      - pgdb
  
  pgdb:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: m2vira
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@m2vira.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8888:80"

volumes:
  data:
  pgadmin:  