global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "identity.api"
    static_configs:
      - targets: ["host.docker.internal:5001"]
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: "otel-collector"
    scrape_interval: 5s
    static_configs:
      - targets: ["otel-collector:8889"]
      - targets: ["otel-collector:8888"]
